model:
  model_type: deepseek-ai/DeepSeek-R1-Distill-Llama-8B

eval:
  tasks: [hendrycks_math500]
  batch_size: 1
  limit: null
  log_samples: false
  add_bos_token: false
  num_fewshot: 0
  apply_chat_template: true
  fewshot_as_multiturn: false
  gen_kwargs: null
  max_gen_toks: 8192

save:
  run_dir: save/DeepSeek-R1-Distill-Llama-8B-vllm/
  logger: math500.log

vllm:
  dtype: float16
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.75
  enforce_eager: true
  max_model_len: 32768
  trust_remote_code: true
