model:
  model_type: black-forest-labs/FLUX.1-dev

dataset:
  name: "coco_200"
  prompt_dir: "image/coco_1024/prompts.txt"

save:
  run_dir: "save/FLUX.1-dev/"
  logger: "inference.log"

eval:
  metrics: [ir, clip, fid, lpips, psnr, ssim]
  fid_real_folder: "image/coco_1024"