quantization:
  xqtype: mxex
  wqtype: mxex

  # quantize before non-linear
  quant_before_hadamard: False
  quant_before_silu: False
  quant_before_rms_norm: False

  # quantize output layer (lm head)
  quant_output_layer: False

  # quantize post-rope QK (input of QK^T)
  quant_post_rope_q: False

  # quantize post-rope K and V
  quant_k_cache: False
  quant_v_cache: False
  quant_4b_kv: False # if True, use KV4, otherwise use act quantizer

  # quantize attention weight
  quant_attn_wgt: False

block_quant:
  act_mbit: 3
  act_block_size: 16
  act_l2_block_size: 2
  act_sc_bit: 8
  act_l2_sc_bit: 1

  wgt_mbit: 3
  wgt_block_size: 16
  wgt_l2_block_size: 2
  wgt_sc_bit: 8
  wgt_l2_sc_bit: 1
