quantization:
  xqtype: mxfp
  wqtype: mxfp

  # quantize before non-linear
  quant_before_hadamard: False
  quant_before_silu: False
  quant_before_rms_norm: False

  # quantize output layer (lm head)
  quant_output_layer: False

  # quantize post-rope Q (input of QK^T)
  quant_post_rope_q: False

  # quantize post-rope K and V
  quant_4b_kv: False # if True, use KV4, otherwise use act quantizer
  quant_k_cache: False
  quant_v_cache: False

  # quantize attention weight
  quant_attn_wgt: False

block_quant:
  act_ebit: 2
  act_mbit: 1
  act_block_size: 16
  act_sc_ebit: 5
  act_sc_mbit: 3

  wgt_ebit: 2
  wgt_mbit: 1
  wgt_block_size: 16
  wgt_sc_ebit: 5
  wgt_sc_mbit: 3

  # per tensor scale for NVFP format
  wgt_per_tensor_scale: False
  act_per_tensor_scale: False

  # use subnormal for scaling factor
  scale_allow_subnormal: False

  # use rounding for qk_proj in MXFP format
  qk_mx_round: False

  # use ceil for scale quantization
  act_scale_use_ceil: False
  wgt_scale_use_ceil: False

accumulation:
  type: fp16_quant
  group_size: 128
  quant_block_size: 32
