model:
  model_type: PixArt-alpha/PixArt-Sigma-XL-2-1024-MS

dataset:
  name: "coco_1024"
  prompt_dir: "image/coco_1024/coco_1024.txt"

save:
  run_dir: "save/PixArt-Sigma-XL-2-1024-MS/"
  logger: "inference.log"

eval:
  # metrics: [ir, clip, fid, lpips, psnr]
  metrics: [ssim]
  fid_real_folder: "image/coco_1024"