model:
  model_type: PixArt-alpha/PixArt-Sigma-XL-2-1024-MS

dataset:
  name: "coco_200"
  prompt_dir: "image/coco_1024/prompts.txt"

save:
  run_dir: "save/PixArt-Sigma-XL-2-1024-MS/"
  logger: "inference.log"

eval:
  metrics: [ir, clip, fid, lpips, psnr, ssim]
  fid_real_folder: "image/coco_1024"